### ISSUE TITLE
Metadata added into the NetCDF should abide by a standard

### ISSUE THREAD

**Issue by j-harbin** [j-harbin/oceToNetCDF#58]
Right now, all `metadata` in the `oce` objects get dumped into the attributes. It instead should be following a standard. For example, for IOOS (Integrated Ocean Observing System) one standards that exist is: The netCDF created should be included. I'll familiarize myself with the standards and likely introduce appropriate changes. The `odfMetadataCheck` will likely be helpful here.

**Comment by j-harbin** [comment]
When looking up these standards, I will be using Emily's Net CDF Standards v2.7.2_Aug13 document.

**Comment by j-harbin** [comment]
A list of required and suggested Global attributes can be found at https://wiki.esipfed.org/Attribute_Convention_for_Data_Discovery_1-3#Global_Attributes

**Comment by j-harbin** [comment]
I'll need to update the vignette for the new `standardMetadata` function.

**Comment by j-harbin** [comment]
The new updated workflow (although long) is as follows:

![ctd_rcm_diagram](https://user-images.githubusercontent.com/58750538/225346851-6cbb41bf-2f26-40fa-8d93-74a36bb6e7a5.png)

I'm okay with the workflow being long because this is a complicated topic. All functions are properly documented and I believe this diagram will be extremely helpful for those new to this package. Note: as of now, IOOS standards only applies to RCM and CTD. I'll be working on adcp data now.

**Comment by dankelley** [comment]
I wonder if extending the notation to permit choices other than TRUE or FALSE might help.  For example, the "Is the file origin ODF?" box could say "File origin" and then it could have streams named "ODF", "Matlab" and "other".  (The "other" gives an error msg for now.)

Just a thought.

PS. I don't think it's too long or too complicated.  Rather, I agree with you that such a diagram is *extremely* helpful.

**Comment by j-harbin** [comment]
Thanks for the feedback @dankelley. If time permits, I'll make the appropriate change.

This issue has been fixed for adp types in commit 0ed0a99baf7e688654969008573a198a3167830c of the ioos branch. I'll close this issue.
